name: Unit Test by PHPUnit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  container:
    name: Docker ${{ matrix.php }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '5.6.40-zts-alpine', '7.0.33-zts-alpine', '7.1.33-zts-alpine', '7.2.34-zts-alpine', '7.3.32-zts-alpine', '7.4.25-zts-alpine', '8.0.12-alpine' ]
    container:
      image: docker://php:${{ matrix.php }}
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - uses: actions/checkout@master

      - name: Install wget
        run: apk add wget

      - name: Install composer bin
        run: |
          wget -O /usr/local/bin/composer https://mirrors.aliyun.com/composer/composer.phar
          chmod +x /usr/local/bin/composer

      - name: Install php library
        run: php vendor/bin/phpunit

      - name: PHP Unit Test
        run: php vendor/bin/phpunit
